export { WelcomeSection } from './welcome/welcome'
export { CitySection } from './city/city'
export { ObjectSection } from './object/object'
export { LocationSection } from './location/location'
export { RelaxSection } from './relax/relax'
export { HorizontalSection } from './horizontal/horizontal'
export { VideoSection } from './video/video'
export { PlansSection } from './plans/plans'
