export { Header } from './ui/header/header'
export { InterstroyLogo } from './ui/logo/logo'
export { MyImage } from './ui/image/image'
export { MobileSlider } from './ui/slider/mobile-slider'
export { CustomScrollbar } from './ui/scrollbar/custom-scrollbar'

export { useScrollbar } from './model/use-scrollbar'

export { PhoneIcon } from './ui/icons/phone'
export { ChartIcon } from './ui/icons/chart'
export { BedIcon } from './ui/icons/bed'
export { ClassIcon } from './ui/icons/class'
export { EatIcon } from './ui/icons/eat'
export { SafetyIcon } from './ui/icons/safety'
export { ServiceIcon } from './ui/icons/service'
export { SpaIcon } from './ui/icons/spa'
export { PeopleIcon } from './ui/icons/people'
